### ISSUE TITLE
iTunesArtwork extension

### ISSUE THREAD

**Issue by johnmullaney** [m2orris/GIMP-scripts#2]
I think the iTunesArtwork and iTunesArtwork@2x should have a .png added to them as that is what the iTunes connect expects.
Otherwise fantastic timesaver!!

**Comment by m2orris** [comment]
Great to hear that people are using this pulgin and it is saving people time.

Unless you are speaking of a recent change, according to Apple, iTunesArtwork and iTunesArtwork@2x should NOT have .png added. 

If you search for "iTunesArtwork" in the Organizer, it will return the following among others:

ref: http://developer.apple.com/library/ios/#documentation/userexperience/conceptual/mobilehig/IconsImages/IconsImages.html
"With the exception of the App Store icon—which must be named iTunesArtwork—you can name your app icon anything you want."

ref: http://developer.apple.com/library/ios/#qa/qa1686/_index.html
"Image Size (px) | File Name | Used For |Required Status
512x512 | iTunesArtwork | Ad Hoc iTunes | Optional but recommended"

ref: http://developer.apple.com/library/ios/#documentation/iphone/conceptual/iphoneosprogrammingguide/App-RelatedResources/App-RelatedResources.html  
"The name of this file must be iTunesArtwork and not have a filename extension. The high resolution version of this icon should be 1024 x 1024 pixels and have the name iTunesArtwork@2x."
